### PR TITLE
Update pyproject.toml to the new PEP 621 syntax

### PR DESCRIPTION
**Pull request by magv**
This updates pyproject.toml and a SConstruct to the shiny new PEP 621 syntax, as an example of how it should look like. The setup2toml script will also put the config under the `project` key, not `tool.enscons`, but it'll still use the old setuptools-alike keys (which are still supported). Writing an automated converter is possible in principle, but it's an effort for another time maybe.

### CODE REVIEW

**Comment by dholth** [comment]
Nice. If this means setup2toml produces invalid pyproject.toml then we might keep its output under tool.enscons for now, but our own pyproject.toml can stay shiny.

**Comment by magv** [comment]
It should still be valid, as in: accepted by enscons, just not really PEP 621. Personally I don't feel bad about putting non-PEP 621 keys into `[project]`I, as it is always up to the installation tool to interpret it anyway. But if you prefer I can make setup2toml still output the old format (i.e. `[tool.enscons]`).

BTW, I did not test setup2toml beyond making sure it has no syntax errors (I don't use setuptools myself).

**Comment by dholth** [comment]
... I need to update setup2toml so that it is suitable as an `enscons.init` (create a new project without a starter setup.py). If it outputs the standard format, you might use setup2toml even if you don't plan on using enscons...

**Comment by dholth** [comment]
I noticed setuptools uses the [options] key, maybe we should too.

Oh, just in setup.cfg not project.toml.

**Pull request merged**
