### PR TITLE
Update the list of manylinux tags

### PR DESCRIPTION
**Pull request by magv**
Add `manylinux2014` and `manylinux_2_24` platform tags to cover all the currently available manylinux images.

Nowadays manylinux uses a regular naming scheme from PEP 600, so it makes sense to support that in the future, but for the moment this should be enough to get the correct tags in the existing containers.

The problem with supporting PEP 600 is that in principle there is no longer a small fixed set of tags, but rather a whole enumeration of `manylinux_x_y`, so `enscons.tags.sys_tags()` would either need to list a whole lot more of combinations, or would need to be rethought somehow. (For my usage the needed API is actually just "return the correct manylinux platform tag if inside a manylinux container otherwise return whatever").

### CODE REVIEW

**Comment by magv** [comment]
I've just found out (by trial) that the current pip does not list `manylinux2010` among its tags: it starts with `manylinux2014`, then `manylinux_2_17` and up till `manylinux_2_xx`, so one can't actually install `manylinux1` or `manylinux2010` wheels any more. This is unfortunate for enscons, because at the moment `manylinux2010` is the newest tag it knows about. Now normally this isn't a major problem: if one just renames the wheel file to have the needed tag, then e.g. uploading to PyPI and installing with pip works fine. Unfortunately that doesn't cut it for [piwheels](https://www.piwheels.org): it rebuilds PyPI packages for Raspberry Pi machines, and it really needs the tags to be correct; the project I'm converting to enscons can't be installed from it at the moment, because the tag it has there is `manylinux2010` (as given by enscons).

Anyway, I've updated the `_linux_platforms` logic to match [PEP 600](https://www.python.org/dev/peps/pep-0600/), so hopefully this will fix everything.

**Comment by dholth** [comment]
enscons should depend on a new version of packaging, which includes tags functionality.

**Comment by magv** [comment]
Oh, wow.

And now I see that there's this at the top of `tags.py`:
```
# Vendored from https://github.com/pypa/packaging/ until its next release:
```

OK, it seems packaging version 20.5 is the first one that reports the tags correctly on my machine. So should we bump the minimum dependency version of `packaging`, drop `enscons/tags.py` completely, and reexport `packaging.tags` instead?

**Comment by dholth** [comment]
Yes, we should depend on a recent version of packaging and replace our vendored version.

**Comment by magv** [comment]
Here is the proposed change. Note that `import enscons.tags` no longer works, so any users that relied on that will see breakage, but I'm not sure that there were any (they can use `packaging.tags` instead). In principle it's possible to add `tags.py` that would just say `from packaging.tags import *`, which would prevent any such breakage, but I don't know if it's worth the effort.

**Comment by magv** [comment]
On my machine `enscons.get_binary_tag()` comes out as `cp36-cp36m-linux_x86_64`, `enscons.get_universal_tag()` as `py2.py3-none-any`, and `enscons.get_abi3_tag()` as `cp36-abi3-manylinux_2_26_x86_64`. The previous enscons showed the same, except that `enscons.get_abi3_tag()` was `cp36-abi3-manylinux2010_x86_64`.

Which results would you prefer?

(For my use I'm actually looking for a way to get `py3-none-manylinux_2_26_x86_64`, so I intend to use `packaging` directly).

**Comment by dholth** [comment]
I would prefer a non-manylinux abi3 tag. Usually you will not build on a manylinux system.

**Comment by magv** [comment]
No more `manylinux` in `get_abi3_tag()`. Right now it comes out as `cp36-abi3-linux_x86_64` on my machine, which is consistent with `get_binary_tag()`.

BTW, the docstring for `get_abi3_tag()` says that it returns `None` if there are no abi3 tags, but it actually returns `get_binary_tag()`. Should the comment of the return value be updated?

**Comment by dholth** [comment]
Yes, thank you

**Comment by magv** [comment]
I've updated the comment.

**Pull request merged**
